name: Build Android App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-apks
        path: |
          app/build/outputs/apk/debug/
        retention-days: 7
